spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

management:
  endpoint:
    health:
      show-details: always

homepedia:
  batch:
    startup-enabled: ${HOMEPEDIA_BATCH_STARTUP_ENABLED:false}
  insee:
    import-enabled: true
  geo:
    import-enabled: true
  dpe:
    import-enabled: ${HOMEPEDIA_DPE_ENABLED:false}
    csv-path: ${HOMEPEDIA_DPE_CSV_PATH:}
  health:
    import-enabled: ${HOMEPEDIA_HEALTH_ENABLED:false}
    csv-path: ${HOMEPEDIA_HEALTH_CSV_PATH:}
  dvf:
    zip-path: ${HOMEPEDIA_DVF_ZIP_PATH:}
  import:
    reviews:
      enabled: ${IMPORT_REVIEWS_ENABLED:false}
  scheduler:
    enabled: ${HOMEPEDIA_SCHEDULER_ENABLED:false}
    zone: ${HOMEPEDIA_SCHEDULER_ZONE:Europe/Paris}
    insee:
      cron: ${HOMEPEDIA_SCHEDULER_INSEE_CRON:-}
    geo:
      cron: ${HOMEPEDIA_SCHEDULER_GEO_CRON:-}
    dvf:
      cron: ${HOMEPEDIA_SCHEDULER_DVF_CRON:-}
    dpe:
      cron: ${HOMEPEDIA_SCHEDULER_DPE_CRON:-}
    health:
      cron: ${HOMEPEDIA_SCHEDULER_HEALTH_CRON:-}
    reviews:
      cron: ${HOMEPEDIA_SCHEDULER_REVIEWS_CRON:-}

logging:
  level:
    com.homepedia: INFO
