spring:
  application:
    name: homepedia-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/homepedia}
    username: ${SPRING_DATASOURCE_USERNAME:homepedia}
    password: ${SPRING_DATASOURCE_PASSWORD:homepedia}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
