spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homepedia
    username: homepedia
    password: homepedia

homepedia:
  dvf:
    zip-path:
  dpe:
    import-enabled: false
    csv-path:
  health:
    import-enabled: false
    csv-path:
  insee:
    import-enabled: false
  geo:
    import-enabled: false
  import:
    reviews:
      enabled: false

logging:
  level:
    com.homepedia: DEBUG
