branches:
  - main

tagFormat: "data-pipeline-v${version}"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: "backend/data-pipeline/CHANGELOG.md"
  - - "@semantic-release/exec"
    - prepareCmd: >
        mvn -f backend/data-pipeline/pom.xml versions:set
        -DnewVersion=${nextRelease.version}
        -DgenerateBackupPoms=false
  - - "@semantic-release/git"
    - assets:
        - "backend/data-pipeline/CHANGELOG.md"
        - "backend/data-pipeline/pom.xml"
      message: "chore(release): data-pipeline-v${nextRelease.version} [skip ci]"
  - "@semantic-release/gitlab"
